<?php
/**
 * SimpleLockTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Evva\AirKey
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVVA AirKey Cloud API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v16.20.7
 * Contact: office-wien@evva.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Evva\AirKey;

/**
 * SimpleLockTest Class Doc Comment
 *
 * @category    Class
 * @description Model that describes a lock in a simple form defined in the access control system.
 * @package     Evva\AirKey
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SimpleLockTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SimpleLock"
     */
    public function testSimpleLock()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "lock_type"
     */
    public function testPropertyLockType()
    {
    }

    /**
     * Test attribute "lock_identifier"
     */
    public function testPropertyLockIdentifier()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "additional_information"
     */
    public function testPropertyAdditionalInformation()
    {
    }
}
